/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRekomendasiTanamRouteImport } from './routes/_layout/rekomendasi-tanam'
import { Route as LayoutPrediksiHargaRouteImport } from './routes/_layout/prediksi-harga'
import { Route as LayoutPetaWilayahRouteImport } from './routes/_layout/peta-wilayah'
import { Route as LayoutKesesuaianLahanRouteImport } from './routes/_layout/kesesuaian-lahan'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAppRouteImport } from './routes/_layout/app'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRekomendasiTanamRoute = LayoutRekomendasiTanamRouteImport.update({
  id: '/rekomendasi-tanam',
  path: '/rekomendasi-tanam',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrediksiHargaRoute = LayoutPrediksiHargaRouteImport.update({
  id: '/prediksi-harga',
  path: '/prediksi-harga',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPetaWilayahRoute = LayoutPetaWilayahRouteImport.update({
  id: '/peta-wilayah',
  path: '/peta-wilayah',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKesesuaianLahanRoute = LayoutKesesuaianLahanRouteImport.update({
  id: '/kesesuaian-lahan',
  path: '/kesesuaian-lahan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppRoute = LayoutAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/app': typeof LayoutAppRoute
  '/items': typeof LayoutItemsRoute
  '/kesesuaian-lahan': typeof LayoutKesesuaianLahanRoute
  '/peta-wilayah': typeof LayoutPetaWilayahRoute
  '/prediksi-harga': typeof LayoutPrediksiHargaRoute
  '/rekomendasi-tanam': typeof LayoutRekomendasiTanamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/app': typeof LayoutAppRoute
  '/items': typeof LayoutItemsRoute
  '/kesesuaian-lahan': typeof LayoutKesesuaianLahanRoute
  '/peta-wilayah': typeof LayoutPetaWilayahRoute
  '/prediksi-harga': typeof LayoutPrediksiHargaRoute
  '/rekomendasi-tanam': typeof LayoutRekomendasiTanamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/app': typeof LayoutAppRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/kesesuaian-lahan': typeof LayoutKesesuaianLahanRoute
  '/_layout/peta-wilayah': typeof LayoutPetaWilayahRoute
  '/_layout/prediksi-harga': typeof LayoutPrediksiHargaRoute
  '/_layout/rekomendasi-tanam': typeof LayoutRekomendasiTanamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/app'
    | '/items'
    | '/kesesuaian-lahan'
    | '/peta-wilayah'
    | '/prediksi-harga'
    | '/rekomendasi-tanam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/app'
    | '/items'
    | '/kesesuaian-lahan'
    | '/peta-wilayah'
    | '/prediksi-harga'
    | '/rekomendasi-tanam'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/app'
    | '/_layout/items'
    | '/_layout/kesesuaian-lahan'
    | '/_layout/peta-wilayah'
    | '/_layout/prediksi-harga'
    | '/_layout/rekomendasi-tanam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/rekomendasi-tanam': {
      id: '/_layout/rekomendasi-tanam'
      path: '/rekomendasi-tanam'
      fullPath: '/rekomendasi-tanam'
      preLoaderRoute: typeof LayoutRekomendasiTanamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/prediksi-harga': {
      id: '/_layout/prediksi-harga'
      path: '/prediksi-harga'
      fullPath: '/prediksi-harga'
      preLoaderRoute: typeof LayoutPrediksiHargaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/peta-wilayah': {
      id: '/_layout/peta-wilayah'
      path: '/peta-wilayah'
      fullPath: '/peta-wilayah'
      preLoaderRoute: typeof LayoutPetaWilayahRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kesesuaian-lahan': {
      id: '/_layout/kesesuaian-lahan'
      path: '/kesesuaian-lahan'
      fullPath: '/kesesuaian-lahan'
      preLoaderRoute: typeof LayoutKesesuaianLahanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app': {
      id: '/_layout/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof LayoutAppRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAppRoute: typeof LayoutAppRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutKesesuaianLahanRoute: typeof LayoutKesesuaianLahanRoute
  LayoutPetaWilayahRoute: typeof LayoutPetaWilayahRoute
  LayoutPrediksiHargaRoute: typeof LayoutPrediksiHargaRoute
  LayoutRekomendasiTanamRoute: typeof LayoutRekomendasiTanamRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAppRoute: LayoutAppRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutKesesuaianLahanRoute: LayoutKesesuaianLahanRoute,
  LayoutPetaWilayahRoute: LayoutPetaWilayahRoute,
  LayoutPrediksiHargaRoute: LayoutPrediksiHargaRoute,
  LayoutRekomendasiTanamRoute: LayoutRekomendasiTanamRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
